import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // But you can create a sidebar manually
  tutorialSidebar: [
    // Root introduction docs
    'intro-gpt',
    'intro-human',

    // Basics section with custom ordering
    {
      type: 'category',
      label: 'Basics',
      items: [
        {
          type: 'category',
          label: 'Introduction To Multimedia',
          link: {type: 'doc', id: 'basics/introduction_to_multimedia'},
          items: ['basics/color_space'],
        },
        'basics/resolution',
        'basics/frame_rates',
        'basics/bandwidth',
        'basics/codecs',
        'basics/compression',
        'basics/stream_formats',
        'basics/file_formats',
      ],
    },

    // Other sections auto-generated
    {type: 'autogenerated', dirName: 'amagi'},
    {type: 'autogenerated', dirName: 'advanced'},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
